增加选择是否使用 Enter 而不是 Ctrl+Enter 发送信息的设置
SlimeNull/OpenGptChat pull request #6
Opened 2023-03-25 03:23 UTC by Saplonily

可能有点不合规范(?
感谢帮忙指明下(

2023-03-25 03:33 UTC, SlimeNull requested changes
不要直接操作 UI, 尽量使用绑定, 在 ViewModel 中定义 Modifier, 然后 UI 绑定过去.

2023-03-25 04:06 UTC, Saplonily commented
现在呢...?

2023-03-25 12:54 UTC, SlimeNull commented
有个要求, 用户的配置信息必须是能实时生效的, 但看你目前的代码, ModifierKey 和 ToolTip 只会在页面初始化的时候根据配置变更

2023-03-26 10:27 UTC, closed without merging

2023-03-26 10:28 UTC, Saplonily commented
懒了, 嘤嘤嘤, close罢(